[project]
name = "ag2-a2a"
version = "0.1.0"
description = "MCP Mypy agent using A2A and AG2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
<<<<<<< HEAD
    "ag2[mcp,openai,a2a,websockets]>=0.10.0",
    "fastapi>=0.110.0",
    "mypy>=1.10.0",
    "uvicorn[standard]>=0.30.0",
=======
    "ag2[mcp,openai,a2a]>=0.10.0",
    "mypy>=1.10.0",
>>>>>>> 30c9ccc (feat: update AG2 example using 0.10 A2A builtins (#392))
]
